### PR TITLE
Formsy input: Button addon support

### PR DESCRIPTION
**Pull request by erzzo**
A new release would really help me. Thanks

### CODE REVIEW

**Comment by twisty** [comment]
Hi, thanks for this. Have just published a new release.

**Comment by erzzo** [comment]
great, thanks

**Comment by jcalfee** [comment]
What about styling and click events for the outer addon container?  I included an addon span with an onClick event but the span is very difficult to click the click area is so small.  If I could put the event handler on the parent container that would be better.

Same thing with styling, a border or background color change on the addon is very small.. It is necessary to apply this to the parent container.

The formsy react container I'm referring to has the class `input-group-addon` ..

**Comment by twisty** [comment]
@jcalfee, how about adding a class to the top level component...

```jsx
<Input
  elementWrapperClassName="my-component"
  name="button-before"
  value=""
  label="Button before"
  type="text"
  buttonBefore={
    <button className="btn btn-default" type="button">
     Go!
    </button>
  }
/>
```

...then using css descendant selectors to target the addon group wrapper:

```css
.my-component .input-group-addon {
  border: 10px solid black;
}
```

**Pull request merged**
